### ISSUE TITLE
CI Improvements

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#160]
## Description
Our CI is good, but it could be _better_.

The complex thing here is #164, which we'll handle in a separate issue.

## TODO
- [x] Add caching
- [ ] Add clippy
- [ ] Separate test from check

**Comment by davidkuhta** [comment]
Check out the issue-160 branch for a CI workflow based on [CI w/ GH actions and Rust](https://www.homeops.dev/continuous-integration-with-github-actions-and-rust/) using [actions-rs](https://actions-rs.github.io):

```yaml
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: stable
  TOOLCHAIN_PROFILE: minimal

jobs:
  lints:
    name: Run cargo fmt and cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA dev
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
          components: rustfmt, clippy
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA dev
        run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: ${{ env.TOOLCHAIN_PROFILE }}
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Run cargo test --no-run
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: "--no-run"
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          RUST_TEST_THREADS: 1
        with:
          command: test
          args: "-p hotham --lib"
```
